### ISSUE TITLE
Erreur dans les logs

### ISSUE THREAD

**Issue by michelgrolet** [merlleu/ldv-dashbot#2]
Une idée ? Ça à l'air de marcher quand même.
```
Traceback (most recent call last):
  File "/app/ldv_watcher/grades.py", line 17, in start_grades_loop
    new = ldv_dashbot.DataClass.json(bot.get_grades())
  File "/app/ldv_dashbot/__init__.py", line 171, in get_grades
    for i in u[3].contents:
IndexError: list index out of range
```

**Comment by merlleu** [comment]
Le bot n'arrive pas à récupérer les notes, ça n'impacte pas la partie appel mais juste les notifications quand des notes sont ajoutées sur le site.
On doit parser le html pour en extraire ces données, je dois refaire cette partie à l'occasion.
